version: '2.1'

services:
  mysql:
    networks:
      - my-network
    image: mysql:5.7.21
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: "limites"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  prometheus:
    networks:
      - my-network
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana: #tem que colocar http://prometheus:9090 na configuracao
    networks:
      - my-network
    image: grafana/grafana:7.3.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
networks:
  my-network:
    name: my-network